### ISSUE TITLE
Restore uptake curves downloads 

### ISSUE THREAD

**Issue by DominikRafacz** [hadexversum/HaDeXGUI#13]

**Comment by DominikRafacz** [comment]
Question: they are meant to work for each selected peptide, but currently UC plots allow for selecting only one peptide... mr. president, how to live?

**Comment by werpuc** [comment]
No, the "download" option is for whole peptide pool, no matter which peptides are selected in the plot tab. 

Selecting peptide from the table is only for the plot and data tab.

**Comment by DominikRafacz** [comment]
ahh, okay, I see; I'll finish that today or tomorrow then
